apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    env: monitor
  name: prometheus-deploy
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30001
  selector:
    env: monitor
  type: NodePort
status:
  loadBalancer: {}
